MasterDetail/Models/LogEntry.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace MasterDetail.Models
{
    public class LogEntry
    {
        public Int64 LogEntryID { get; set; }

        [Display(Name = "Date")]
        public DateTime LogDate { get; set; }
        public string Logger { get; set; }

        [Display(Name = "Level")]
        public string LogLevel { get; set; }
        public string Thread { get; set; }

        [Display(Name = "Entity")]
        public string EntityFormalNamePlural { get; set; }

        [Display(Name = "Key")]
        public int EntityKeyValue { get; set; }

        [Display(Name = "User")]
        public string UserName { get; set; }
        public string Message { get; set; }
        public string Exception { get; set; }
    }
}

MasterDetail/Controllers/LogEntriesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using MasterDetail.DataLayer;
using MasterDetail.Models;

namespace MasterDetail.Controllers
{
    public class LogEntriesController : Controller
    {
        private ApplicationDbContext _applicationDbContext = new ApplicationDbContext();


        public ActionResult LogEntries(string entityFormalNamePlural, int entityKeyValue)
        {

            IEnumerable<LogEntry> logEntries = _applicationDbContext.LogEntries.Where(le =>
                le.EntityFormalNamePlural == entityFormalNamePlural &&
                le.EntityKeyValue == entityKeyValue)
                .OrderByDescending(le => le.LogDate);

            return PartialView("_LogEntries", logEntries);
        }


        public async Task<ActionResult> Index()
        {
            return View(await _applicationDbContext.LogEntries.ToListAsync());
        }


        public async Task<ActionResult> Details(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            LogEntry logEntry = await _applicationDbContext.LogEntries.FindAsync(id);
            if (logEntry == null)
            {
                return HttpNotFound();
            }
            return View(logEntry);
        }


        public ActionResult Create()
        {
            return View();
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "LogEntryID,LogDate,Logger,LogLevel,Thread,EntityFormalNamePlural,EntityKeyValue,UserName,Message,Exception")] LogEntry logEntry)
        {
            if (ModelState.IsValid)
            {
                _applicationDbContext.LogEntries.Add(logEntry);
                await _applicationDbContext.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            return View(logEntry);
        }


        public async Task<ActionResult> Edit(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            LogEntry logEntry = await _applicationDbContext.LogEntries.FindAsync(id);
            if (logEntry == null)
            {
                return HttpNotFound();
            }
            return View(logEntry);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "LogEntryID,LogDate,Logger,LogLevel,Thread,EntityFormalNamePlural,EntityKeyValue,UserName,Message,Exception")] LogEntry logEntry)
        {
            if (ModelState.IsValid)
            {
                _applicationDbContext.Entry(logEntry).State = EntityState.Modified;
                await _applicationDbContext.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(logEntry);
        }


        public async Task<ActionResult> Delete(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            LogEntry logEntry = await _applicationDbContext.LogEntries.FindAsync(id);
            if (logEntry == null)
            {
                return HttpNotFound();
            }
            return View(logEntry);
        }


        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(long id)
        {
            LogEntry logEntry = await _applicationDbContext.LogEntries.FindAsync(id);
            _applicationDbContext.LogEntries.Remove(logEntry);
            await _applicationDbContext.SaveChangesAsync();
            return RedirectToAction("Index");
        }


        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                _applicationDbContext.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

MasterDetail/Views/LogEntries/Create.cshtml
@model MasterDetail.Models.LogEntry

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>LogEntry</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.LogDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LogDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LogDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Logger, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Logger, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Logger, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LogLevel, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LogLevel, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LogLevel, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Thread, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Thread, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Thread, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EntityFormalNamePlural, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EntityFormalNamePlural, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.EntityFormalNamePlural, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EntityKeyValue, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EntityKeyValue, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.EntityKeyValue, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.UserName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.UserName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.UserName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Message, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Message, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Message, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Exception, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Exception, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Exception, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

MasterDetail/Views/LogEntries/Delete.cshtml
@model MasterDetail.Models.LogEntry

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>LogEntry</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.LogDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LogDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Logger)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Logger)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LogLevel)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LogLevel)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Thread)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Thread)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EntityFormalNamePlural)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EntityFormalNamePlural)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EntityKeyValue)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EntityKeyValue)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.UserName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UserName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Message)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Message)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Exception)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Exception)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

MasterDetail/Views/LogEntries/Details.cshtml
@model MasterDetail.Models.LogEntry

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>LogEntry</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.LogDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LogDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Logger)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Logger)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LogLevel)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LogLevel)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Thread)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Thread)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EntityFormalNamePlural)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EntityFormalNamePlural)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EntityKeyValue)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EntityKeyValue)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.UserName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UserName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Message)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Message)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Exception)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Exception)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.LogEntryID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

MasterDetail/Views/LogEntries/Edit.cshtml
@model MasterDetail.Models.LogEntry

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>LogEntry</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.LogEntryID)

        <div class="form-group">
            @Html.LabelFor(model => model.LogDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LogDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LogDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Logger, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Logger, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Logger, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LogLevel, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LogLevel, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LogLevel, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Thread, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Thread, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Thread, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EntityFormalNamePlural, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EntityFormalNamePlural, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.EntityFormalNamePlural, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EntityKeyValue, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EntityKeyValue, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.EntityKeyValue, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.UserName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.UserName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.UserName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Message, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Message, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Message, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Exception, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Exception, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Exception, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

MasterDetail/Views/LogEntries/Index.cshtml
@model IEnumerable<MasterDetail.Models.LogEntry>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.LogDate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Logger)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.LogLevel)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Thread)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.EntityFormalNamePlural)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.EntityKeyValue)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.UserName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Message)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Exception)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.LogDate)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Logger)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.LogLevel)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Thread)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.EntityFormalNamePlural)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.EntityKeyValue)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.UserName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Message)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Exception)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.LogEntryID }) |
            @Html.ActionLink("Details", "Details", new { id=item.LogEntryID }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.LogEntryID })
        </td>
    </tr>
}

</table>

MasterDetail/Views/LogEntries/_LogEntries.cshtml
@model IEnumerable<MasterDetail.Models.LogEntry>

<div class="panel panel-default">
    <div class="panel-heading">
        <strong>Audit Trail</strong>
    </div>
    
    <div style="height: 300px; overflow-y: scroll;">
        <table class="table table-hover table-striped table-condensed small">
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.LogDate)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.LogLevel)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.UserName)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Message)
                </th>
                <th></th>
            </tr>

            @foreach (var item in Model)
            {
                <tr>
                    <td class="text-nowrap">
                        @Html.DisplayFor(modelItem => item.LogDate)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.LogLevel)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.UserName)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Message)
                    </td>
                    <td>
                        @Html.ActionLink("Details", "Details", "LogEntries", new { id = item.LogEntryID }, new { @class = "btn btn-default btn-xs" })
                    </td>
                </tr>
            }

        </table>
    </div>
</div>