MasterDetail/Controllers/LaborsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using MasterDetail.DataLayer;
using MasterDetail.Models;

namespace MasterDetail.Controllers
{
    public class LaborsController : Controller
    {
        private ApplicationDbContext _applicationDbContext = new ApplicationDbContext();


        public async Task<ActionResult> Index(int workOrderId, bool? readOnly)
        {
            ViewBag.WorkOrderId = workOrderId;
            var labors = _applicationDbContext.Labors
                .Where(l => l.WorkOrderId == workOrderId)
                .OrderBy(l => l.ServiceItemCode);

            string partialViewName = readOnly == true ? "_IndexReadOnly" : "_Index";
            return PartialView(partialViewName, await labors.ToListAsync());
        }


        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Labor labor = await _applicationDbContext.Labors.FindAsync(id);
            if (labor == null)
            {
                return HttpNotFound();
            }
            return View(labor);
        }


        public ActionResult Create(int workOrderId)
        {
            Labor labor = new Labor();
            labor.WorkOrderId = workOrderId;
            return PartialView("_Create", labor);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "LaborId,WorkOrderId,ServiceItemCode,ServiceItemName,LaborHours,Rate,PercentComplete,Notes")] Labor labor)
        {
            if (ModelState.IsValid)
            {
                _applicationDbContext.Labors.Add(labor);
                await _applicationDbContext.SaveChangesAsync();

                Log4NetHelper.Log(String.Format("Labor item {0} has been added to work order {1} for {2} hours at ${3:#,###.00}/hr.", labor.ServiceItemCode, labor.WorkOrderId, labor.LaborHours, labor.Rate), LogLevel.INFO, "WorkOrders", labor.WorkOrderId, User.Identity.Name, null);

                return Json(new { success = true });
            }

            return PartialView("_Create", labor);
        }


        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Labor labor = await _applicationDbContext.Labors.FindAsync(id);
            if (labor == null)
            {
                return HttpNotFound();
            }
            return PartialView("_Edit", labor);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "LaborId,WorkOrderId,ServiceItemCode,ServiceItemName,LaborHours,Rate,PercentComplete,Notes")] Labor labor)
        {
            if (ModelState.IsValid)
            {
                _applicationDbContext.Entry(labor).State = EntityState.Modified;
                await _applicationDbContext.SaveChangesAsync();

                Log4NetHelper.Log(String.Format("Labor item {0} has been updated in work order {1} to {2} hours at ${3:#,###.00}/hr.", labor.ServiceItemCode, labor.WorkOrderId, labor.LaborHours, labor.Rate), LogLevel.INFO, "WorkOrders", labor.WorkOrderId, User.Identity.Name, null);

                return Json(new { success = true });
            }
            return PartialView("_Edit", labor);
        }


        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Labor labor = await _applicationDbContext.Labors.FindAsync(id);
            if (labor == null)
            {
                return HttpNotFound();
            }
            return PartialView("_Delete", labor);
        }


        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            Labor labor = await _applicationDbContext.Labors.FindAsync(id);
            _applicationDbContext.Labors.Remove(labor);
            await _applicationDbContext.SaveChangesAsync();

            Log4NetHelper.Log(String.Format("Labor item {0} has been deleted from work order {1}.", labor.ServiceItemCode, labor.WorkOrderId), LogLevel.INFO, "WorkOrders", labor.WorkOrderId, User.Identity.Name, null);

            return Json(new { success = true });
        }


        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                _applicationDbContext.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

MasterDetail/Controllers/PartsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using MasterDetail.DataLayer;
using MasterDetail.Models;

namespace MasterDetail.Controllers
{
    public class PartsController : Controller
    {
        private ApplicationDbContext _applicationDbContext = new ApplicationDbContext();


        public async Task<ActionResult> Index(int workOrderId, bool? readOnly)
        {
            ViewBag.WorkOrderId = workOrderId;
            var parts = _applicationDbContext.Parts
                .Where(p => p.WorkOrderId == workOrderId)
                .OrderBy(p => p.InventoryItemCode);

            string partialViewName = readOnly == true ? "_IndexReadOnly" : "_Index";
            return PartialView(partialViewName, await parts.ToListAsync());
        }


        public ActionResult Create(int workOrderId)
        {
            Part part = new Part();
            part.WorkOrderId = workOrderId;
            return PartialView("_Create", part);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "PartId,WorkOrderId,InventoryItemCode,InventoryItemName,Quantity,UnitPrice,Notes,IsInstalled")] Part part)
        {
            if (ModelState.IsValid)
            {
                _applicationDbContext.Parts.Add(part);
                await _applicationDbContext.SaveChangesAsync();

                Log4NetHelper.Log(String.Format("Part {0} has been added to work order {1} for {2} at ${3:#,###.00} each.", part.InventoryItemCode, part.WorkOrderId, part.Quantity, part.UnitPrice), LogLevel.INFO, "WorkOrders", part.WorkOrderId, User.Identity.Name, null);

                return Json(new {success = true});
            }

            return PartialView("_Create", part);
        }


        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Part part = await _applicationDbContext.Parts.FindAsync(id);
            if (part == null)
            {
                return HttpNotFound();
            }
            return PartialView("_Edit", part);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "PartId,WorkOrderId,InventoryItemCode,InventoryItemName,Quantity,UnitPrice,Notes,IsInstalled")] Part part)
        {
            if (ModelState.IsValid)
            {
                _applicationDbContext.Entry(part).State = EntityState.Modified;
                await _applicationDbContext.SaveChangesAsync();

                Log4NetHelper.Log(String.Format("Part {0} has been updated in work order {1} to {2} at ${3:#,###.00} each.", part.InventoryItemCode, part.WorkOrderId, part.Quantity, part.UnitPrice), LogLevel.INFO, "WorkOrders", part.WorkOrderId, User.Identity.Name, null);

                return Json(new { success = true });
            }
            return PartialView("_Edit", part);
        }


        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Part part = await _applicationDbContext.Parts.FindAsync(id);
            if (part == null)
            {
                return HttpNotFound();
            }
            return PartialView("_Delete", part);
        }


        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            Part part = await _applicationDbContext.Parts.FindAsync(id);
            _applicationDbContext.Parts.Remove(part);
            await _applicationDbContext.SaveChangesAsync();

            Log4NetHelper.Log(String.Format("Part {0} has been deleted from work order {1}.", part.InventoryItemCode, part.WorkOrderId), LogLevel.INFO, "WorkOrders", part.WorkOrderId, User.Identity.Name, null);

            return Json(new { success = true });
        }


        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                _applicationDbContext.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

MasterDetail/Controllers/WorkOrdersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using MasterDetail.DataLayer;
using MasterDetail.Models;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;

namespace MasterDetail.Controllers
{
    [Authorize]
    public class WorkOrdersController : Controller
    {
        private ApplicationDbContext _applicationDbContext = new ApplicationDbContext();


        public async Task<ActionResult> Index()
        {
            var workOrders = _applicationDbContext.WorkOrders.Include(w => w.CurrentWorker).Include(w => w.Customer);
            return View(await workOrders.ToListAsync());
        }


        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            WorkOrder workOrder = await _applicationDbContext.WorkOrders.FindAsync(id);
            if (workOrder == null)
            {
                return HttpNotFound();
            }
            return View(workOrder);
        }


        public ActionResult Create()
        {
            ViewBag.CustomerId = new SelectList(_applicationDbContext.Customers.Where(c => c.Cloaked == false), "CustomerId", "CompanyName");
            return View();
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "WorkOrderId,CustomerId,OrderDateTime,TargetDateTime,DropDeadDateTime,Description,WorkOrderStatus,CertificationRequirements,CurrentWorkerId")] WorkOrder workOrder)
        {
            if (ModelState.IsValid)
            {
                workOrder.CurrentWorkerId = User.Identity.GetUserId();
                _applicationDbContext.WorkOrders.Add(workOrder);
                await _applicationDbContext.SaveChangesAsync();

                Log4NetHelper.Log(String.Format("Work order {0} created", workOrder.WorkOrderId), LogLevel.INFO, workOrder.EntityFormalNamePlural, workOrder.WorkOrderId, User.Identity.Name, null);

                return RedirectToAction("Edit", new { controller = "WorkOrders", action = "Edit", Id = workOrder.WorkOrderId});
            }

            ViewBag.CustomerId = new SelectList(_applicationDbContext.Customers.Where(c => c.Cloaked == false), "CustomerId", "AccountNumber", workOrder.CustomerId);
            return View(workOrder);
        }


        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            WorkOrder workOrder = await _applicationDbContext.WorkOrders.FindAsync(id);
            if (workOrder == null)
            {
                return HttpNotFound();
            }

            // If a different user has claimed the work order since you refreshed the work list, redirect to work list with error message.
            if (workOrder.CurrentWorkerId != null && workOrder.CurrentWorkerId != User.Identity.GetUserId())
            {
                ApplicationUserManager userManager = HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>();
                string claimedUserName = userManager.FindById(workOrder.CurrentWorkerId).UserName;

                string message = String.Format("User {0} has claimed work order {1} before user {2} could, and so the work order remains claimed by {0}", claimedUserName, workOrder.WorkOrderId, User.Identity.GetUserName());

                TempData["MessageToClient"] = message;

                Log4NetHelper.Log(message, LogLevel.INFO, workOrder.EntityFormalNamePlural, workOrder.WorkOrderId, User.Identity.Name, null);

                return RedirectToAction("Index", "WorkList");
            }

            if (workOrder.Status.Substring(workOrder.Status.Length - 3, 3) != "ing")
                return View("Claim", workOrder);

            return View(workOrder.Status, workOrder);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "WorkOrderId,CustomerId,OrderDateTime,TargetDateTime,DropDeadDateTime,Description,WorkOrderStatus,CertificationRequirements,CurrentWorkerId,ReworkNotes,RowVersion")] WorkOrder workOrder, string command)
        {
            if (ModelState.IsValid)
            {
                // Populate Parts and Labors
                workOrder.Parts = _applicationDbContext.Parts.Where(p => p.WorkOrderId == workOrder.WorkOrderId).ToList();
                workOrder.Labors = _applicationDbContext.Labors.Where(l => l.WorkOrderId == workOrder.WorkOrderId).ToList();

                PromotionResult promotionResult = new PromotionResult();

                if (command == "Save")
                {
                    promotionResult.Success = true;
                    promotionResult.Message = String.Format("Changes to work order {0} have been successfully saved.", workOrder.Id);
                    Log4NetHelper.Log(promotionResult.Message, LogLevel.INFO, workOrder.EntityFormalNamePlural, workOrder.Id, User.Identity.Name, null);
                }
                else if (command == "Claim")
                    promotionResult = workOrder.ClaimWorkListItem(User.Identity.GetUserId());
                else if (command == "Relinquish")
                    promotionResult = workOrder.RelinquishWorkListItem();
                else
                    promotionResult = workOrder.PromoteWorkListItem(command);

                if (!promotionResult.Success)
                    TempData["MessageToClient"] = promotionResult.Message;

                _applicationDbContext.Entry(workOrder).State = EntityState.Modified;

                try
                {
                    await _applicationDbContext.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (command == "Claim")
                        TempData["MessageToClient"] = String.Format("Someone else has claimed work order {0} since you retrieved it.", workOrder.WorkOrderId);
                    else
                        TempData["MessageToClient"] = String.Format("Someone else has modified work order {0} since you retrieved it.  Your changes have not been applied.", workOrder.WorkOrderId);

                    return RedirectToAction("Index", "WorkList");
                }

                if (command == "Claim" && promotionResult.Success)
                    return RedirectToAction("Edit", workOrder.WorkOrderId);

                return RedirectToAction("Index", "WorkList");
            }

            return View(workOrder);
        }


        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            WorkOrder workOrder = await _applicationDbContext.WorkOrders.FindAsync(id);
            if (workOrder == null)
            {
                return HttpNotFound();
            }
            return View(workOrder);
        }


        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            WorkOrder workOrder = await _applicationDbContext.WorkOrders.FindAsync(id);
            _applicationDbContext.WorkOrders.Remove(workOrder);
            await _applicationDbContext.SaveChangesAsync();
            return RedirectToAction("Index");
        }


        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                _applicationDbContext.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

MasterDetail/Views/WorkOrders/Approving.cshtml
@model MasterDetail.Models.WorkOrder

<h2>Approve Work Order</h2>

<div id="partsModal" class="modal fade in">
    <div class="modal-dialog">
        <div class="modal-content">
            <div id="partsModalContent"></div>
        </div>
    </div>
</div>

<div id="laborsModal" class="modal fade in">
    <div class="modal-dialog">
        <div class="modal-content">
            <div id="laborsModalContent"></div>
        </div>
    </div>
</div>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.WorkOrderId)
        @Html.HiddenFor(model => model.CustomerId)
        @Html.HiddenFor(model => model.CurrentWorkerId)
        @Html.HiddenFor(model => model.RowVersion)

        <div class="row">
            <div class="col-md-5">
                <div class="form-group form-group-sm">
                    @Html.LabelFor(model => model.CustomerId, htmlAttributes: new { @class = "control-label col-md-4" })
                    <div class="col-md-8">
                        @Html.EditorFor(model => model.Customer.CompanyName, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
                    </div>
                </div>

                <div class="form-group form-group-sm">
                    @Html.LabelFor(model => model.OrderDateTime, htmlAttributes: new { @class = "control-label col-md-4" })
                    <div class="col-md-8">
                        @Html.EditorFor(model => model.OrderDateTime, "DateReadOnly")
                    </div>
                </div>

                <div class="form-group form-group-sm">
                    @Html.LabelFor(model => model.TargetDateTime, htmlAttributes: new { @class = "control-label col-md-4" })
                    <div class="col-md-8">
                        @Html.EditorFor(model => model.TargetDateTime, "DateReadOnly")
                        @Html.ValidationMessageFor(model => model.TargetDateTime, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group form-group-sm">
                    @Html.LabelFor(model => model.DropDeadDateTime, htmlAttributes: new { @class = "control-label col-md-4" })
                    <div class="col-md-8">
                        @Html.EditorFor(model => model.DropDeadDateTime, "DateReadOnly")
                        @Html.ValidationMessageFor(model => model.DropDeadDateTime, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group form-group-sm">
                    @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-4" })
                    <div class="col-md-8">
                        @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
                        @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group form-group-sm">
                    @Html.LabelFor(model => model.ReworkNotes, htmlAttributes: new { @class = "control-label col-md-4" })
                    <div class="col-md-8">
                        @Html.EditorFor(model => model.ReworkNotes, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.ReworkNotes, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group form-group-sm">
                    @Html.LabelFor(model => model.WorkOrderStatus, htmlAttributes: new { @class = "control-label col-md-4" })
                    <div class="col-md-8">
                        @Html.EditorFor(model => model.WorkOrderStatus, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
                    </div>
                </div>

                <div class="form-group form-group-sm">
                    @Html.LabelFor(model => model.CertificationRequirements, htmlAttributes: new { @class = "control-label col-md-4" })
                    <div class="col-md-8">
                        @Html.EditorFor(model => model.CertificationRequirements, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
                        @Html.ValidationMessageFor(model => model.CertificationRequirements, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group form-group-sm">
                    @Html.LabelFor(model => model.CurrentWorker.FullName, "Current Worker", htmlAttributes: new { @class = "control-label col-md-4" })
                    <div class="col-md-8">
                        @Html.EditorFor(model => model.CurrentWorker.FullName, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
                    </div>
                </div>
            </div>

            <div class="col-md-7">
                @{Html.RenderAction("LogEntries", "LogEntries", new { entityFormalNamePlural = "WorkOrders", entityKeyValue = Model.WorkOrderId });}
            </div>
        </div>

        @{Html.RenderAction("Index", "Parts", new { workOrderId = Model.WorkOrderId, readOnly = true });}

        @{Html.RenderAction("Index", "Labors", new { workOrderId = Model.WorkOrderId, readOnly = true });}
        
        <div class="col-md-5">
            <div class="form-group form-group-sm">
                @Html.LabelFor(model => model.Total, htmlAttributes: new { @class = "control-label col-md-4" })
                <div class="col-md-8">
                    @Html.EditorFor(model => model.Total, "CustomNumberFormat", new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
                </div>
            </div>
        </div>
        
        <div class="col-md-7">
            <div class="form-group form-group-sm">
                <button type="submit" name="Command" value="PromoteToApproved" class="btn btn-success">Promote to Approved</button>
                <button type="submit" name="Command" value="DemoteToCreated" class="btn btn-danger">Demote to Created</button>
                <button type="submit" name="Command" value="DemoteToRejected" class="btn btn-danger">Demote to Rejected</button>
                <button type="submit" name="Command" value="DemoteToCanceled" class="btn btn-danger">Demote to Canceled</button>
                <button type="submit" name="Command" value="Relinquish" class="btn btn-warning">Relinquish</button>
            </div>            
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index", "WorkList")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    <script src="~/Scripts/workorder.js"></script>
}

MasterDetail/Views/WorkOrders/Certifying.cshtml
@model MasterDetail.Models.WorkOrder

<h2>Certify Work Order</h2>

<div id="partsModal" class="modal fade in">
    <div class="modal-dialog">
        <div class="modal-content">
            <div id="partsModalContent"></div>
        </div>
    </div>
</div>

<div id="laborsModal" class="modal fade in">
    <div class="modal-dialog">
        <div class="modal-content">
            <div id="laborsModalContent"></div>
        </div>
    </div>
</div>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.WorkOrderId)
        @Html.HiddenFor(model => model.CustomerId)
        @Html.HiddenFor(model => model.CurrentWorkerId)
        @Html.HiddenFor(model => model.RowVersion)

        <div class="row">
            <div class="col-md-5">
                <div class="form-group form-group-sm">
                    @Html.LabelFor(model => model.CustomerId, htmlAttributes: new { @class = "control-label col-md-4" })
                    <div class="col-md-8">
                        @Html.EditorFor(model => model.Customer.CompanyName, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
                    </div>
                </div>

                <div class="form-group form-group-sm">
                    @Html.LabelFor(model => model.OrderDateTime, htmlAttributes: new { @class = "control-label col-md-4" })
                    <div class="col-md-8">
                        @Html.EditorFor(model => model.OrderDateTime, "DateReadOnly")
                    </div>
                </div>

                <div class="form-group form-group-sm">
                    @Html.LabelFor(model => model.TargetDateTime, htmlAttributes: new { @class = "control-label col-md-4" })
                    <div class="col-md-8">
                        @Html.EditorFor(model => model.TargetDateTime, "DateReadOnly")
                        @Html.ValidationMessageFor(model => model.TargetDateTime, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group form-group-sm">
                    @Html.LabelFor(model => model.DropDeadDateTime, htmlAttributes: new { @class = "control-label col-md-4" })
                    <div class="col-md-8">
                        @Html.EditorFor(model => model.DropDeadDateTime, "DateReadOnly")
                        @Html.ValidationMessageFor(model => model.DropDeadDateTime, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group form-group-sm">
                    @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-4" })
                    <div class="col-md-8">
                        @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
                        @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group form-group-sm">
                    @Html.LabelFor(model => model.ReworkNotes, htmlAttributes: new { @class = "control-label col-md-4" })
                    <div class="col-md-8">
                        @Html.EditorFor(model => model.ReworkNotes, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
                        @Html.ValidationMessageFor(model => model.ReworkNotes, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group form-group-sm">
                    @Html.LabelFor(model => model.WorkOrderStatus, htmlAttributes: new { @class = "control-label col-md-4" })
                    <div class="col-md-8">
                        @Html.EditorFor(model => model.WorkOrderStatus, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
                    </div>
                </div>

                <div class="form-group form-group-sm">
                    @Html.LabelFor(model => model.CertificationRequirements, htmlAttributes: new { @class = "control-label col-md-4" })
                    <div class="col-md-8">
                        @Html.EditorFor(model => model.CertificationRequirements, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.CertificationRequirements, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group form-group-sm">
                    @Html.LabelFor(model => model.CurrentWorker.FullName, "Current Worker", htmlAttributes: new { @class = "control-label col-md-4" })
                    <div class="col-md-8">
                        @Html.EditorFor(model => model.CurrentWorker.FullName, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
                    </div>
                </div>
            </div>

            <div class="col-md-7">
                @{Html.RenderAction("LogEntries", "LogEntries", new { entityFormalNamePlural = "WorkOrders", entityKeyValue = Model.WorkOrderId });}
            </div>
        </div>

        @{Html.RenderAction("Index", "Parts", new { workOrderId = Model.WorkOrderId });}

        @{Html.RenderAction("Index", "Labors", new { workOrderId = Model.WorkOrderId });}
        
        <div class="col-md-5">
            <div class="form-group form-group-sm">
                @Html.LabelFor(model => model.Total, htmlAttributes: new { @class = "control-label col-md-4" })
                <div class="col-md-8">
                    @Html.EditorFor(model => model.Total, "CustomNumberFormat", new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
                </div>
            </div>
        </div>
        
        <div class="col-md-7">
            <div class="form-group form-group-sm">
                <button type="submit" name="Command" value="Save" class="btn btn-default">Save</button>
                <button type="submit" name="Command" value="PromoteToCertified" class="btn btn-success">Promote to Certified</button>
                <button type="submit" name="Command" value="Relinquish" class="btn btn-warning">Relinquish</button>
            </div>            
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index", "WorkList")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    <script src="~/Scripts/workorder.js"></script>
}